services:
  postgres:
    image: postgres:16
    container_name: imdb-postgres
    environment:
      POSTGRES_USER: imdb
      POSTGRES_PASSWORD: imdb
      POSTGRES_DB: imdb
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./db/postgres:/migrations   # tu siedzi schema.sql
      - ./data:/data                # tu będą dumpy IMDb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U imdb -d imdb || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  mysql:
    image: mysql:8.4
    container_name: imdb-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: imdb
      MYSQL_USER: imdb
      MYSQL_PASSWORD: imdb
    command:
      - "--local-infile=ON"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./data:/data
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "imdb", "-pimdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongo:
    image: mongo:8.0
    container_name: imdb-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: imdb
      MONGO_INITDB_ROOT_PASSWORD: imdb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./data:/data
    healthcheck:
      test: ["CMD-SHELL", "mongosh --username imdb --password imdb --eval 'db.adminCommand(\"ping\")' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  cassandra:
    image: cassandra:5
    container_name: imdb-cassandra
    environment:
      MAX_HEAP_SIZE: 2G
      HEAP_NEWSIZE: 512M
      CASSANDRA_CLUSTER_NAME: "imdb_cluster"
      CASSANDRA_NUM_TOKENS: 16
    ports:
      - "9042:9042"
    volumes:
      - cassandra_data:/var/lib/cassandra
      - ./data:/data
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'DESCRIBE KEYSPACES' || exit 1"]
      interval: 30s
      timeout: 20s
      retries: 10

volumes:
  pg_data:
  mysql_data:
  mongo_data:
  cassandra_data:
