services:
  postgres:
    image: postgres:16
    container_name: imdb-postgres
    environment:
      POSTGRES_USER: imdb
      POSTGRES_PASSWORD: imdb
      POSTGRES_DB: imdb
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./data:/data

  mysql:
    image: mysql:8.4
    container_name: imdb-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: imdb
      MYSQL_USER: imdb
      MYSQL_PASSWORD: imdb
    command: ["--local-infile=ON"]
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./data:/data

  mariadb:
    image: mariadb:12.1.2
    container_name: imdb-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: imdb
      MYSQL_USER: imdb
      MYSQL_PASSWORD: imdb
    command: ["--local-infile=1"]
    ports:
      - "3308:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./data:/data

  mongo-8:
    image: mongo:8.0
    container_name: imdb-mongo-8
    environment:
      MONGO_INITDB_ROOT_USERNAME: imdb
      MONGO_INITDB_ROOT_PASSWORD: imdb
    ports:
      - "27018:27017"
    volumes:
      - mongo_data_8:/data/db
      - ./data:/data

  mongo-7:
    image: mongo:7.0.0
    container_name: imdb-mongo-7
    environment:
      MONGO_INITDB_ROOT_USERNAME: imdb
      MONGO_INITDB_ROOT_PASSWORD: imdb
    ports:
      - "27019:27017"
    volumes:
      - mongo_data_7:/data/db
      - ./data:/data

  cassandra:
    image: cassandra:5
    container_name: imdb-cassandra
    environment:
      MAX_HEAP_SIZE: 2G
      HEAP_NEWSIZE: 512M
      CASSANDRA_CLUSTER_NAME: "imdb_cluster"
      CASSANDRA_NUM_TOKENS: 16
    ports:
      - "9042:9042"
    volumes:
      - cassandra_data:/var/lib/cassandra
      - ./data:/data
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'DESCRIBE KEYSPACES' || exit 1"]
      interval: 30s
      timeout: 20s
      retries: 10

volumes:
  pg_data:
  mysql_data:
  mariadb_data:
  mongo_data_7:
  mongo_data_8:
  cassandra_data:
